import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-programmatic-ad-supply-path-fee-audit",
  "engine": "recovery",
  "title": "Programmatic Ad Supply-Path Fee Audit",
  "shortTitle": "Programmatic Ad Supply-Path Fee Audit",
  "tagline": "Expose programmatic fee leakage and optimize supply paths through impression-level bid, clearing-price, and intermediary reconciliation.",
  "industry": "Advertising Cost Transparency",
  "buyer": "Brands, publishers, and media agencies",
  "uiPort": 4730,
  "apiPort": 5730,
  "accent": "#1d4ed8",
  "currency": "USD",
  "primaryOutcome": "Programmatic Ad Supply-Path Fee Audit converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect insertion orders, DSP logs, SSP logs, bid requests, impressions, clearing prices, tech fees, data fees, verification, invalid traffic, invoices, and payments in one accountable workflow. Expose programmatic fee leakage and optimize supply paths through impression-level bid, clearing-price, and intermediary reconciliation.",
  "calculation": {
    "actualKey": "chargedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Charged or Paid Amount",
    "expectedLabel": "Evidence-Supported Amount",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Programmatic Ad Supply-Path Fee Audit evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("insertion-order-library","PAS01","Insertion order library","Execute insertion order library using insertion orders, DSP logs, SSP logs, bid requests, impressions, clearing prices, tech fees, data fees, verification, invalid traffic, invoices, and payments.","Produce a governed insertion order library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Campaign / Supply Chain","text","Campaign / Supply Chain · Standard Case"],["caseReference","Insertion order library Reference","text","PAS01-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1703750],["supportedAmount","Evidence-Supported Amount","currency",1431150],["domainDriver","Supply Node","select","DSP",["DSP","SSP","Exchange reseller"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Insertion order library case","Campaign creative registry case","DSP log ingestion case","SSP log ingestion case","Bid request matching case"]}),
feature("campaign-creative-registry","PAS02","Campaign creative registry","Execute campaign creative registry using insertion orders, DSP logs, SSP logs, bid requests, impressions, clearing prices, tech fees, data fees, verification, invalid traffic, invoices, and payments.","Produce a governed campaign creative registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Campaign / Supply Chain","text","Campaign / Supply Chain · Standard Case"],["caseReference","Campaign creative registry Reference","text","PAS02-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1703750],["supportedAmount","Evidence-Supported Amount","currency",1431150],["domainDriver","Supply Node","select","DSP",["DSP","SSP","Exchange reseller"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Insertion order library case","Campaign creative registry case","DSP log ingestion case","SSP log ingestion case","Bid request matching case"]}),
feature("dsp-log-ingestion","PAS03","DSP log ingestion","Execute dsp log ingestion using insertion orders, DSP logs, SSP logs, bid requests, impressions, clearing prices, tech fees, data fees, verification, invalid traffic, invoices, and payments.","Produce a governed dsp log ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Campaign / Supply Chain","text","Campaign / Supply Chain · Standard Case"],["caseReference","DSP log ingestion Reference","text","PAS03-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1703750],["supportedAmount","Evidence-Supported Amount","currency",1431150],["domainDriver","Supply Node","select","DSP",["DSP","SSP","Exchange reseller"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Insertion order library case","Campaign creative registry case","DSP log ingestion case","SSP log ingestion case","Bid request matching case"]}),
feature("ssp-log-ingestion","PAS04","SSP log ingestion","Execute ssp log ingestion using insertion orders, DSP logs, SSP logs, bid requests, impressions, clearing prices, tech fees, data fees, verification, invalid traffic, invoices, and payments.","Produce a governed ssp log ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Campaign / Supply Chain","text","Campaign / Supply Chain · Standard Case"],["caseReference","SSP log ingestion Reference","text","PAS04-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1703750],["supportedAmount","Evidence-Supported Amount","currency",1431150],["domainDriver","Supply Node","select","DSP",["DSP","SSP","Exchange reseller"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Insertion order library case","Campaign creative registry case","DSP log ingestion case","SSP log ingestion case","Bid request matching case"]}),
feature("bid-request-matching","PAS05","Bid request matching","Execute bid request matching using insertion orders, DSP logs, SSP logs, bid requests, impressions, clearing prices, tech fees, data fees, verification, invalid traffic, invoices, and payments.","Produce a governed bid request matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Campaign / Supply Chain","text","Campaign / Supply Chain · Standard Case"],["caseReference","Bid request matching Reference","text","PAS05-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1703750],["supportedAmount","Evidence-Supported Amount","currency",1431150],["domainDriver","Supply Node","select","DSP",["DSP","SSP","Exchange reseller"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Insertion order library case","Campaign creative registry case","DSP log ingestion case","SSP log ingestion case","Bid request matching case"]}),
feature("impression-event-matching","PAS06","Impression event matching","Execute impression event matching using insertion orders, DSP logs, SSP logs, bid requests, impressions, clearing prices, tech fees, data fees, verification, invalid traffic, invoices, and payments.","Produce a governed impression event matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Campaign / Supply Chain","text","Campaign / Supply Chain · Standard Case"],["caseReference","Impression event matching Reference","text","PAS06-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1703750],["supportedAmount","Evidence-Supported Amount","currency",1431150],["domainDriver","Supply Node","select","DSP",["DSP","SSP","Exchange reseller"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Insertion order library case","Campaign creative registry case","DSP log ingestion case","SSP log ingestion case","Bid request matching case"]}),
feature("clearing-price-reconstruction","PAS07","Clearing price reconstruction","Execute clearing price reconstruction using insertion orders, DSP logs, SSP logs, bid requests, impressions, clearing prices, tech fees, data fees, verification, invalid traffic, invoices, and payments.","Produce a governed clearing price reconstruction decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Campaign / Supply Chain","text","Campaign / Supply Chain · Standard Case"],["caseReference","Clearing price reconstruction Reference","text","PAS07-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1703750],["supportedAmount","Evidence-Supported Amount","currency",1431150],["domainDriver","Supply Node","select","DSP",["DSP","SSP","Exchange reseller"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Insertion order library case","Campaign creative registry case","DSP log ingestion case","SSP log ingestion case","Bid request matching case"]}),
feature("dsp-fee-calculation","PAS08","DSP fee calculation","Execute dsp fee calculation using insertion orders, DSP logs, SSP logs, bid requests, impressions, clearing prices, tech fees, data fees, verification, invalid traffic, invoices, and payments.","Produce a governed dsp fee calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Campaign / Supply Chain","text","Campaign / Supply Chain · Standard Case"],["caseReference","DSP fee calculation Reference","text","PAS08-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1703750],["supportedAmount","Evidence-Supported Amount","currency",1431150],["domainDriver","Supply Node","select","DSP",["DSP","SSP","Exchange reseller"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Insertion order library case","Campaign creative registry case","DSP log ingestion case","SSP log ingestion case","Bid request matching case"]}),
feature("ssp-fee-calculation","PAS09","SSP fee calculation","Execute ssp fee calculation using insertion orders, DSP logs, SSP logs, bid requests, impressions, clearing prices, tech fees, data fees, verification, invalid traffic, invoices, and payments.","Produce a governed ssp fee calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Campaign / Supply Chain","text","Campaign / Supply Chain · Standard Case"],["caseReference","SSP fee calculation Reference","text","PAS09-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1703750],["supportedAmount","Evidence-Supported Amount","currency",1431150],["domainDriver","Supply Node","select","DSP",["DSP","SSP","Exchange reseller"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Insertion order library case","Campaign creative registry case","DSP log ingestion case","SSP log ingestion case","Bid request matching case"]}),
feature("data-fee-audit","PAS10","Data fee audit","Execute data fee audit using insertion orders, DSP logs, SSP logs, bid requests, impressions, clearing prices, tech fees, data fees, verification, invalid traffic, invoices, and payments.","Produce a governed data fee audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Campaign / Supply Chain","text","Campaign / Supply Chain · Standard Case"],["caseReference","Data fee audit Reference","text","PAS10-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1703750],["supportedAmount","Evidence-Supported Amount","currency",1431150],["domainDriver","Supply Node","select","DSP",["DSP","SSP","Exchange reseller"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Insertion order library case","Campaign creative registry case","DSP log ingestion case","SSP log ingestion case","Bid request matching case"]}),
feature("verification-fee-audit","PAS11","Verification fee audit","Execute verification fee audit using insertion orders, DSP logs, SSP logs, bid requests, impressions, clearing prices, tech fees, data fees, verification, invalid traffic, invoices, and payments.","Produce a governed verification fee audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Campaign / Supply Chain","text","Campaign / Supply Chain · Standard Case"],["caseReference","Verification fee audit Reference","text","PAS11-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1703750],["supportedAmount","Evidence-Supported Amount","currency",1431150],["domainDriver","Supply Node","select","DSP",["DSP","SSP","Exchange reseller"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Insertion order library case","Campaign creative registry case","DSP log ingestion case","SSP log ingestion case","Bid request matching case"]}),
feature("invalid-traffic-adjustment","PAS12","Invalid traffic adjustment","Execute invalid traffic adjustment using insertion orders, DSP logs, SSP logs, bid requests, impressions, clearing prices, tech fees, data fees, verification, invalid traffic, invoices, and payments.","Produce a governed invalid traffic adjustment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Campaign / Supply Chain","text","Campaign / Supply Chain · Standard Case"],["caseReference","Invalid traffic adjustment Reference","text","PAS12-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1703750],["supportedAmount","Evidence-Supported Amount","currency",1431150],["domainDriver","Supply Node","select","DSP",["DSP","SSP","Exchange reseller"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Insertion order library case","Campaign creative registry case","DSP log ingestion case","SSP log ingestion case","Bid request matching case"]}),
feature("invoice-reconciliation","PAS13","Invoice reconciliation","Execute invoice reconciliation using insertion orders, DSP logs, SSP logs, bid requests, impressions, clearing prices, tech fees, data fees, verification, invalid traffic, invoices, and payments.","Produce a governed invoice reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Campaign / Supply Chain","text","Campaign / Supply Chain · Standard Case"],["caseReference","Invoice reconciliation Reference","text","PAS13-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1703750],["supportedAmount","Evidence-Supported Amount","currency",1431150],["domainDriver","Supply Node","select","DSP",["DSP","SSP","Exchange reseller"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Insertion order library case","Campaign creative registry case","DSP log ingestion case","SSP log ingestion case","Bid request matching case"]}),
feature("supply-path-exception-workflow","PAS14","Supply-path exception workflow","Execute supply-path exception workflow using insertion orders, DSP logs, SSP logs, bid requests, impressions, clearing prices, tech fees, data fees, verification, invalid traffic, invoices, and payments.","Produce a governed supply-path exception workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Campaign / Supply Chain","text","Campaign / Supply Chain · Standard Case"],["caseReference","Supply-path exception workflow Reference","text","PAS14-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1703750],["supportedAmount","Evidence-Supported Amount","currency",1431150],["domainDriver","Supply Node","select","DSP",["DSP","SSP","Exchange reseller"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Insertion order library case","Campaign creative registry case","DSP log ingestion case","SSP log ingestion case","Bid request matching case"]}),
feature("campaign-publisher-analytics","PAS15","Campaign publisher analytics","Execute campaign publisher analytics using insertion orders, DSP logs, SSP logs, bid requests, impressions, clearing prices, tech fees, data fees, verification, invalid traffic, invoices, and payments.","Produce a governed campaign publisher analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Campaign / Supply Chain","text","Campaign / Supply Chain · Standard Case"],["caseReference","Campaign publisher analytics Reference","text","PAS15-2026-001"],["chargedAmount","Charged or Paid Amount","currency",1703750],["supportedAmount","Evidence-Supported Amount","currency",1431150],["domainDriver","Supply Node","select","DSP",["DSP","SSP","Exchange reseller"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Insertion order library case","Campaign creative registry case","DSP log ingestion case","SSP log ingestion case","Bid request matching case"]})
]);
